server:
  port : 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: usbw
#    url: jdbc:mysql://106.12.86.1:3306/jeecg?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnect=true
#    username: root
#    password: password


